apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-monitored-redis
  name: my-monitored-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-monitored-redis
  template:
    metadata:
      labels:
        app: my-monitored-redis
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        image: redis:3.2.11
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 6379
          timeoutSeconds: 5
        name: my-monitored-redis
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
