apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-monitored-redis-exporter
  name: my-monitored-redis-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: metrics
  selector:
    app: my-monitored-redis-exporter
  type: ClusterIP
