apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-monitored-redis
  name: my-monitored-redis
  namespace: monitoring
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  selector:
    app: my-monitored-redis
  sessionAffinity: None
  type: ClusterIP
